### PR TITLE
feat: Run build command in build mode

### PR DESCRIPTION
**Pull request by bencergazda**
PR for #19

### CODE REVIEW

**Comment by birtles** [comment]
This looks great. Thanks for fixing the types too!

I wonder if we should add an option for disabling/enabling the build step?

I frequently use this plugin in a situation where I don't want the `web-ext build` step except when running in CI (since during development I load the extension unpacked). I still need the plugin enabled during development when running in watch mode.

**Comment by bencergazda** [comment]
> I wonder if we should add an option for disabling/enabling the build step?

Yes, that makes sense.

Also, there are a few build-related parameters (see https://github.com/mozilla/web-ext/blob/1e265f85966268b650c6d6be94842c8a0cf45f74/src/cmd/build.js#L245) that we could consider adding to `WebExtPluginOptions`. I am thinking in particular of these: `overwriteDest` or `filename`.

`asNeedeed` seems to work like a watch mode, but I'm not pretty sure I would use it.

**Comment by birtles** [comment]
> Also, there are a few build-related parameters (see https://github.com/mozilla/web-ext/blob/1e265f85966268b650c6d6be94842c8a0cf45f74/src/cmd/build.js#L245) that we could consider adding to `WebExtPluginOptions`. I am thinking in particular of `overwriteDest` and `filename`.

Oh yes, `overwriteDest` and `filename` would be great to have.

Do you mind adding them before I merge this? (I'd like to keep the repository in an always-shippable state and I don't think I'd want to ship this without the option to turn off building.)

Also, since building is a pretty significant change in behavior we should probably either:

a) Make it off by default, or
b) Release it as a new major version

I think I prefer (a). What do you think?

**Comment by bencergazda** [comment]
> I think I prefer (a). What do you think?

It would be nice to have it _on_ in build mode, but I wouldn't bump a major version only for this, so I turned off by default, and we will edit the webpack.config.js.

I added a new commit with the new options. Do you like it like this?

**Comment by birtles** [comment]
This is excellent! Thank you very much!

**Pull request merged**
